sensors:
  break_beam_1:
    type: break_beam
    pose:
      xyz: [1.6, 2.25, 0.91]
      rpy: [0, 0, 'pi']
  proximity_sensor_1:
    type: proximity_sensor
    pose:
      xyz: [0.95, 2.6, 0.92]
      rpy: [0, 0, 0]
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [-0.639, -1.915, 1.003]
      rpy: [1.565, 0.937, 0.006]
  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [-0.639, -1.155, 1.003]
      rpy: [1.565, 0.937, 0.006]
  logical_camera_3:
    type: logical_camera
    pose:
      xyz: [-0.639, -0.385, 1.003]
      rpy: [1.565, 0.937, 0.006]
  logical_camera_4:
    type: logical_camera
    pose:
      xyz: [-0.639, 0.407, 1.003]
      rpy: [1.565, 0.937, 0.006]
  logical_camera_5:
    type: logical_camera
    pose:
      xyz: [-0.639, 1.142, 1.003]
      rpy: [1.565, 0.937, 0.006]
  logical_camera_6:
    type: logical_camera
    pose:
      xyz: [-0.639, 1.910, 1.003]
      rpy: [1.565, 0.937, 0.006]
  laser_profiler_1:
    type: laser_profiler
    pose:
      xyz: [1.21, 4, 1.6]
      rpy: ['-pi', 'pi/2', 'pi/2']
